include ../../Makefile.common
ENV=OCAML_LANDMARKS='format=json,output="callgraph.json",threads'
EXTRAS=-thread
LANDMARK_NATIVE=unix.cmxa threads.cmxa landmarks-threads.cmxa
LANDMARK_BATCH=unix.cma threads.cma landmarks-threads.cma

